#!/usr/bin/env python3
"""BoringSSL crypto/err/err_data_generate.go (commit 9fc1c33e), ported line for line.

BoringSSL GENERATES crypto/err/err_data.c with `go run` at build time and its
cmake/go.cmake is FATAL without Go. scripts/build-openlitespeed.sh stubs Go out and
runs this instead, on every OS, so the four OpenLiteSpeed artifacts never depend on a
Go toolchain the runner happens to have.

Proven byte-identical to the Go generator's output for that commit (cmp, 4 Oct 2026).
An EMPTY err_data.c still links libcrypto.a and leaves kOpenSSLReasonValues undefined
until the final openlitespeed link, so the build script checks the symbol with nm.

Usage: run inside boringssl/crypto/err/, stdout is err_data.c.
"""
import os, sys
LIBS = ["NONE","SYS","BN","RSA","DH","EVP","BUF","OBJ","PEM","DSA","X509","ASN1","CONF","CRYPTO","EC","SSL","BIO",
        "PKCS7","PKCS8","X509V3","RAND","ENGINE","OCSP","UI","COMP","ECDSA","ECDH","HMAC","DIGEST","CIPHER","HKDF",
        "TRUST_TOKEN","USER"]
libmap = {n: i + 1 for i, n in enumerate(LIBS)}
OFFSET_MASK = 0x7fff
entries, interned, data = [], {}, bytearray()
def add(key, value):
    assert key & OFFSET_MASK == 0
    off = interned.get(value)
    if off is None:
        off = len(data); assert off & OFFSET_MASK == off, "stringList overflow"
        data.extend(value.encode()); data.append(0); interned[value] = off
    for e in entries:
        if e >> 15 == key >> 15: raise SystemExit("duplicate entry")
    entries.append(key | off)
for name in sorted(os.listdir(".")):
    if not name.endswith(".errordata"): continue
    with open(name, "rb") as f:
        for ln, line in enumerate(f.read().split(b"\n"), 1):
            if not line: continue
            parts = line.split(b",")
            assert len(parts) == 3, (name, ln)
            lib = libmap[parts[0].decode()]; assert lib < 64
            key = int(parts[1]); assert key < 2048
            add(lib << 26 | key << 15, parts[2].decode())
entries.sort(key=lambda e: e >> 15)
out = sys.stdout
out.write("""/* Copyright (c) 2015, Google Inc.
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
 * WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
 * OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
 * CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE. */

 /* This file was generated by err_data_generate.go. */

#include <openssl/base.h>
#include <openssl/err.h>

#include <assert.h>

""")
for i, n in enumerate(LIBS):
    out.write('static_assert(ERR_LIB_%s == %d, "library value changed");\n' % (n, i + 1))
out.write('static_assert(ERR_NUM_LIBS == %d, "number of libraries changed");\n\n' % (len(LIBS) + 1))
out.write("const uint32_t kOpenSSLReasonValues[] = {\n")
for v in entries: out.write("    0x%x,\n" % v)
out.write("};\n\nconst size_t kOpenSSLReasonValuesLen = sizeof(kOpenSSLReasonValues) / sizeof(kOpenSSLReasonValues[0]);\n\n")
out.write('const char kOpenSSLReasonStringData[] =\n    "')
for c in data:
    out.write('\\0"\n    "' if c == 0 else chr(c))
out.write('";\n\n')
